//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1W2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int BlogId { get; set; }
        public string BlogPostTitle { get; set; }
        public string TextPost { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string author { get; set; }
        public string availableFlag { get; set; }
        public string short_description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
