//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1W2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_id { get; set; }
        public string User_firstname { get; set; }
        public string Comment_text { get; set; }
        public Nullable<System.DateTime> date_Comment { get; set; }
        public Nullable<int> FK_Blog_id { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
